//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyOnline.Web.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SurveyConstructor_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SurveyConstructor_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SurveyOnline.Web.Resources.Pages.SurveyConstructor_en", typeof(SurveyConstructor_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Create_Survey {
            get {
                return ResourceManager.GetString("Create Survey", resourceCulture);
            }
        }
        
        internal static string Enter_survey_title {
            get {
                return ResourceManager.GetString("Enter survey title", resourceCulture);
            }
        }
        
        internal static string Enter_description {
            get {
                return ResourceManager.GetString("Enter description", resourceCulture);
            }
        }
        
        internal static string Is_Public {
            get {
                return ResourceManager.GetString("Is Public", resourceCulture);
            }
        }
        
        internal static string Accessible_Users {
            get {
                return ResourceManager.GetString("Accessible Users", resourceCulture);
            }
        }
        
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Remove_Question {
            get {
                return ResourceManager.GetString("Remove Question", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Add_Question {
            get {
                return ResourceManager.GetString("Add Question", resourceCulture);
            }
        }
        
        internal static string Selected_Tags {
            get {
                return ResourceManager.GetString("Selected Tags", resourceCulture);
            }
        }
        
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
    }
}
